# Q2. Row Echelon Form:

 Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations

In [7]:
import numpy as np

seed = 7
np.random.seed(seed)


A = np.random.randint(0, 10, (5, 5))


print("Original Matrix A:")
print(A)
print()

Original Matrix A:
[[4 9 6 3 3]
 [7 7 9 7 8]
 [9 8 7 6 4]
 [0 7 0 7 6]
 [3 5 8 8 7]]



In [8]:
A = A.astype(float)
for i in range(5):
    # Find the first nonzero entry in the current row
    pivot = np.argmax(A[i] != 0)
    if pivot == len(A):  # Skip if row is all zeros
        continue


    A[[i, pivot]] = A[[pivot, i]]


    A[i] /= A[i, i]

    for k in range(i + 1, 5):
        A[k] -= A[k, i] * A[i]


print("Row Echelon Form of Matrix A:")
print(A)

Row Echelon Form of Matrix A:
[[ 1.          2.25        1.5         0.75        0.75      ]
 [-0.          1.          0.17142857 -0.2        -0.31428571]
 [-0.         -0.          1.          0.72727273  1.5       ]
 [ 0.          0.          0.          1.          1.07843137]
 [-0.         -0.         -0.         -0.          1.        ]]
